name: Update README

on:
  schedule:
    # Runs at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: RajnishXCode

      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README with new stats"
          git push origin main
